wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.9.12
    start_time: 1670765800.731199
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 8
      - 23
      4: 3.9.12
      5: 0.13.5
      8:
      - 1
      - 2
      - 3
      - 5
      10:
      - 9
